import * as fs from 'node:fs';
import * as path from 'node:path';
import { CONFIG_FILE, DEFAULT_CONFIG, saveConfig, type BlogConfig } from './config.js';
import { makeFrontmatter } from './build.js';
import { git } from './git.js';

export const THEMES = ['plain', 'nocturne', 'journal', 'pjblog-classic'] as const;

export interface InitOptions {
  dir: string;
  title: string;
  author: string;
  description: string;
  theme: string;
  language: string;
}

export interface InitResult {
  root: string;
  theme: string;
  gitInitialized: boolean;
}

const AGENTS_MD = (title: string) => `# AGENTS.md · ${title}

这是一个 **PJBlog For Finch** 博客工作区。你（Finch）是用户的写作伙伴，和用户一起写日志、一起发布。

## 目录结构

- \`posts/YYYY/\` — 文章源文件（Markdown）。文件名格式：\`YYYY-MM-DD-slug.md\`
- \`pages/\` — 独立页面（如 about.md）
- \`assets/\` — 图片等资源，文章内用相对路径 \`../../assets/xxx.png\` 或站点根 \`assets/xxx.png\`
- \`themes/\` — 主题模板，可以按用户要求直接修改
- \`public/\` — 构建产物，**不要手工编辑**
- \`blog.config.json\` — 站点配置

## 文章规范

每篇文章开头必须有 frontmatter：

\`\`\`markdown
---
title: 文章标题
date: 2026-07-11
tags: [生活, 随笔]
summary: 一句话摘要（可选，缺省取正文前 160 字）
draft: true
---

正文……
\`\`\`

- 写作中的文章保持 \`draft: true\`，预览可见（带草稿标记），发布构建时排除。
- 用户确认定稿后删除 \`draft\` 行。

## 工作方式

- 用户让你写日志时：先用 \`pjblog_new_post\` 创建文件，再充实内容；写完提醒用户可以在浏览器实时预览。
- 用户说「预览」→ 调 \`pjblog_preview\`（action=start / open）。
- 用户说「发布」→ 调 \`pjblog_publish\`：先看变更摘要，用户确认后再带 confirm=true 执行。
- 修改主题样式时直接编辑 \`themes/<当前主题>/\` 下的文件，预览会自动刷新。
`;

const GITIGNORE = `.DS_Store
node_modules/
`;

const PAGES_WORKFLOW = `name: Deploy blog to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v4
`;

function welcomePost(language: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const zh = language.startsWith('zh');
  const fm = makeFrontmatter({
    title: zh ? '你好，世界' : 'Hello, World',
    date: today,
    tags: zh ? ['随笔'] : ['notes'],
    summary: zh ? '这是 PJBlog For Finch 生成的第一篇日志。' : 'The first post generated by PJBlog For Finch.',
  });
  const body = zh
    ? `欢迎来到你的新博客！这篇文章由 **PJBlog For Finch** 自动创建。

## 接下来可以做什么

- 对 Finch 说「帮我写一篇日志」，一起写作
- 说「开启预览」，在浏览器里边写边看
- 说「发布博客」，一键推送到 GitHub Pages

祝写作愉快 ✨
`
    : `Welcome to your new blog! This post was created by **PJBlog For Finch**.

## What's next

- Ask Finch to write a post with you
- Say "start preview" to see changes live in the browser
- Say "publish" to push to GitHub Pages

Happy writing ✨
`;
  return fm + body;
}

function aboutPage(language: string, author: string): string {
  const zh = language.startsWith('zh');
  return makeFrontmatter({ title: zh ? '关于' : 'About', date: new Date().toISOString().slice(0, 10) }) +
    (zh ? `我是 ${author || '这个博客的主人'}。\n\n这个博客由 [PJBlog For Finch](https://finchwork.app) 驱动。\n` : `I'm ${author || 'the owner of this blog'}.\n\nPowered by [PJBlog For Finch](https://finchwork.app).\n`);
}

/**
 * Scaffold a new blog workspace.
 * @param themesSource absolute path to the extension's bundled themes/ directory
 */
export async function initBlog(options: InitOptions, themesSource: string): Promise<InitResult> {
  const root = path.resolve(options.dir);
  if (fs.existsSync(path.join(root, CONFIG_FILE))) {
    throw new Error(`Directory already contains a blog (${CONFIG_FILE} exists): ${root}`);
  }
  fs.mkdirSync(root, { recursive: true });
  if (fs.readdirSync(root).filter((f) => !f.startsWith('.')).length > 0) {
    throw new Error(`Target directory is not empty: ${root}`);
  }

  const theme = (THEMES as readonly string[]).includes(options.theme) ? options.theme : 'plain';
  const config: BlogConfig = {
    ...DEFAULT_CONFIG,
    title: options.title || DEFAULT_CONFIG.title,
    author: options.author,
    description: options.description,
    theme,
    language: options.language || 'zh-CN',
  };

  const year = new Date().getFullYear().toString();
  fs.mkdirSync(path.join(root, 'posts', year), { recursive: true });
  fs.mkdirSync(path.join(root, 'pages'), { recursive: true });
  fs.mkdirSync(path.join(root, 'assets'), { recursive: true });
  fs.mkdirSync(path.join(root, '.github', 'workflows'), { recursive: true });

  // copy all bundled themes so the user can switch freely
  fs.cpSync(themesSource, path.join(root, 'themes'), { recursive: true });

  saveConfig(root, config);
  fs.writeFileSync(path.join(root, 'AGENTS.md'), AGENTS_MD(config.title), 'utf8');
  fs.writeFileSync(path.join(root, '.gitignore'), GITIGNORE, 'utf8');
  fs.writeFileSync(path.join(root, '.github', 'workflows', 'deploy-pages.yml'), PAGES_WORKFLOW, 'utf8');
  fs.writeFileSync(path.join(root, 'posts', year, `${new Date().toISOString().slice(0, 10)}-hello-world.md`), welcomePost(config.language), 'utf8');
  fs.writeFileSync(path.join(root, 'pages', 'about.md'), aboutPage(config.language, config.author), 'utf8');

  // git init + first commit (best effort)
  let gitInitialized = false;
  const init = await git(root, ['init', '-b', 'main']);
  if (init.ok) {
    await git(root, ['add', '-A']);
    const commit = await git(root, ['commit', '-m', 'chore: initialize blog with PJBlog For Finch']);
    gitInitialized = commit.ok;
  }

  return { root, theme, gitInitialized };
}
